---
- hosts: 172.31.0.181
  become: yes
  tasks: 

  - name: i want to execute direct linux commands
    command: hostname -f
    register: fr 

  - name: i want to display first task result
    debug:
      msg: "{{fr}}"

  - name: i want to install git
    apt:
      name: git
      state: present
    when: fr.stderr =="" 

  - name: i want to install tree
    apt:
      name: tree
      state: present
    when: fr.stderr !=""