---
- hosts: 172.31.0.181
  become: yes
  tasks: 
  - include_tasks: myfile.yml 

  - name: install apache2
    apt: 
      name: apache2
      state: present

  - name: copying static file into the servere side
    templet: 
      src: mystaticfile.html
      dest: /var/www/html/index.html
      