---
- hosts: 172.31.0.181
  become: yes
  tasks: 
  - include_tasks: myfile.yml 

  - name: install apache2
    apt: 
      name: apache2
      state: present

  - name: copying static file into the servere side
    template: 
      src: mystaticfile.html
      dest: /var/www/html/index.html
    notify: restartwebservere

  - name: copying a dynamic file into the servere
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    
  - name: i want to copy files from remote into node side
    get_url:
      url: https://get.jenkins.io/war-stable/2.346.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes

  - name: i want to create a folder 
    file:
      path: /home/ubuntu/myfolder22
      state: directory

  handlers:

  - name: restartwebservere
    service: 
      name: apache2
      state: restarted

