---
- hosts: 172.31.0.181
  become: yes
  tasks:

  - name: install git
    apt:
      name: git
      state: present
    tags: mygit

  - name: install tree
    apt: 
      name: tree
      statee: present
    tags: mytree
    ignore_errors: yes

  - name: install wget
    apt:
      name: get
      state: present
    tags: mywget
  
