---
- hosts: mywebservers
  become: yes
  tasks:

  - name: i want to install apache2 on ubuntu nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
  
  - name: i want to start apache2 on ubuntu nodes
    service: 
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name: i want to install apache2 on redhat nodes
    yum: 
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start apache2 on redhat nodes
    service: 
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"
  