---

- name: downlode tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.22/bin/apache-tomcat-10.0.22.tar.gz
    dest: /opt/tomcat/apache-tomcat-10.0.22.tar.gz
    force_basic_auth: yes

- name: extract tomcat tar file
  command:
    cmd: sudo tar xzvf /opt/tomcat/apache-tomcat-10.0.22.tar.gz -C /opt/tomcat --strip-components=1
    creates: LICENSE

